
package client.datahora;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataHoraService", targetNamespace = "http://world.hello/", wsdlLocation = "http://127.0.0.1:9999/datahora?wsdl")
public class DataHoraService
    extends Service
{

    private final static URL DATAHORASERVICE_WSDL_LOCATION;
    private final static WebServiceException DATAHORASERVICE_EXCEPTION;
    private final static QName DATAHORASERVICE_QNAME = new QName("http://world.hello/", "DataHoraService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/datahora?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAHORASERVICE_WSDL_LOCATION = url;
        DATAHORASERVICE_EXCEPTION = e;
    }

    public DataHoraService() {
        super(__getWsdlLocation(), DATAHORASERVICE_QNAME);
    }

    public DataHoraService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAHORASERVICE_QNAME, features);
    }

    public DataHoraService(URL wsdlLocation) {
        super(wsdlLocation, DATAHORASERVICE_QNAME);
    }

    public DataHoraService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAHORASERVICE_QNAME, features);
    }

    public DataHoraService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataHoraService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataHora
     */
    @WebEndpoint(name = "DataHoraPort")
    public DataHora getDataHoraPort() {
        return super.getPort(new QName("http://world.hello/", "DataHoraPort"), DataHora.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataHora
     */
    @WebEndpoint(name = "DataHoraPort")
    public DataHora getDataHoraPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://world.hello/", "DataHoraPort"), DataHora.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAHORASERVICE_EXCEPTION!= null) {
            throw DATAHORASERVICE_EXCEPTION;
        }
        return DATAHORASERVICE_WSDL_LOCATION;
    }

}
