
package client.datahora;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataHora", targetNamespace = "http://world.hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataHora {


    /**
     * 
     * @param a
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayDataHora", targetNamespace = "http://world.hello/", className = "client.datahora.SayDataHora")
    @ResponseWrapper(localName = "sayDataHoraResponse", targetNamespace = "http://world.hello/", className = "client.datahora.SayDataHoraResponse")
    @Action(input = "http://world.hello/DataHora/sayDataHoraRequest", output = "http://world.hello/DataHora/sayDataHoraResponse")
    public String sayDataHora(
        @WebParam(name = "a", targetNamespace = "")
        String a);

}
