
package client.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Helloworld", targetNamespace = "http://world.hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Helloworld {


    /**
     * 
     * @param a
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://world.hello/", className = "client.hello.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://world.hello/", className = "client.hello.SayHelloResponse")
    @Action(input = "http://world.hello/Helloworld/sayHelloRequest", output = "http://world.hello/Helloworld/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "a", targetNamespace = "")
        String a);

}
