
package client.escola;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EscolaService", targetNamespace = "http://exercicio5.world.hello/", wsdlLocation = "http://127.0.0.1:9999/escola?wsdl")
public class EscolaService
    extends Service
{

    private final static URL ESCOLASERVICE_WSDL_LOCATION;
    private final static WebServiceException ESCOLASERVICE_EXCEPTION;
    private final static QName ESCOLASERVICE_QNAME = new QName("http://exercicio5.world.hello/", "EscolaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/escola?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESCOLASERVICE_WSDL_LOCATION = url;
        ESCOLASERVICE_EXCEPTION = e;
    }

    public EscolaService() {
        super(__getWsdlLocation(), ESCOLASERVICE_QNAME);
    }

    public EscolaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESCOLASERVICE_QNAME, features);
    }

    public EscolaService(URL wsdlLocation) {
        super(wsdlLocation, ESCOLASERVICE_QNAME);
    }

    public EscolaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESCOLASERVICE_QNAME, features);
    }

    public EscolaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EscolaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Escola
     */
    @WebEndpoint(name = "EscolaPort")
    public Escola getEscolaPort() {
        return super.getPort(new QName("http://exercicio5.world.hello/", "EscolaPort"), Escola.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Escola
     */
    @WebEndpoint(name = "EscolaPort")
    public Escola getEscolaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exercicio5.world.hello/", "EscolaPort"), Escola.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESCOLASERVICE_EXCEPTION!= null) {
            throw ESCOLASERVICE_EXCEPTION;
        }
        return ESCOLASERVICE_WSDL_LOCATION;
    }

}
