
package client.escola;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Escola", targetNamespace = "http://exercicio5.world.hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Escola {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarAlunos", targetNamespace = "http://exercicio5.world.hello/", className = "client.escola.ListarAlunos")
    @ResponseWrapper(localName = "listarAlunosResponse", targetNamespace = "http://exercicio5.world.hello/", className = "client.escola.ListarAlunosResponse")
    @Action(input = "http://exercicio5.world.hello/Escola/listarAlunosRequest", output = "http://exercicio5.world.hello/Escola/listarAlunosResponse")
    public String listarAlunos();

    /**
     * 
     * @param numero
     * @param estatuto
     * @param nome
     */
    @WebMethod
    @RequestWrapper(localName = "inserirAluno", targetNamespace = "http://exercicio5.world.hello/", className = "client.escola.InserirAluno")
    @ResponseWrapper(localName = "inserirAlunoResponse", targetNamespace = "http://exercicio5.world.hello/", className = "client.escola.InserirAlunoResponse")
    @Action(input = "http://exercicio5.world.hello/Escola/inserirAlunoRequest", output = "http://exercicio5.world.hello/Escola/inserirAlunoResponse")
    public void inserirAluno(
        @WebParam(name = "nome", targetNamespace = "")
        String nome,
        @WebParam(name = "numero", targetNamespace = "")
        int numero,
        @WebParam(name = "estatuto", targetNamespace = "")
        String estatuto);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "removerAluno", targetNamespace = "http://exercicio5.world.hello/", className = "client.escola.RemoverAluno")
    @ResponseWrapper(localName = "removerAlunoResponse", targetNamespace = "http://exercicio5.world.hello/", className = "client.escola.RemoverAlunoResponse")
    @Action(input = "http://exercicio5.world.hello/Escola/removerAlunoRequest", output = "http://exercicio5.world.hello/Escola/removerAlunoResponse")
    public void removerAluno(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
