
package client.imc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMC", targetNamespace = "http://world.hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMC {


    /**
     * 
     * @param peso
     * @param altura
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "indice", targetNamespace = "http://world.hello/", className = "client.imc.Indice")
    @ResponseWrapper(localName = "indiceResponse", targetNamespace = "http://world.hello/", className = "client.imc.IndiceResponse")
    @Action(input = "http://world.hello/IMC/indiceRequest", output = "http://world.hello/IMC/indiceResponse")
    public String indice(
        @WebParam(name = "peso", targetNamespace = "")
        double peso,
        @WebParam(name = "altura", targetNamespace = "")
        double altura);

}
