
package client.imc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IMCService", targetNamespace = "http://world.hello/", wsdlLocation = "http://127.0.0.1:9999/imc?wsdl")
public class IMCService
    extends Service
{

    private final static URL IMCSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMCSERVICE_EXCEPTION;
    private final static QName IMCSERVICE_QNAME = new QName("http://world.hello/", "IMCService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/imc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMCSERVICE_WSDL_LOCATION = url;
        IMCSERVICE_EXCEPTION = e;
    }

    public IMCService() {
        super(__getWsdlLocation(), IMCSERVICE_QNAME);
    }

    public IMCService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMCSERVICE_QNAME, features);
    }

    public IMCService(URL wsdlLocation) {
        super(wsdlLocation, IMCSERVICE_QNAME);
    }

    public IMCService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMCSERVICE_QNAME, features);
    }

    public IMCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMCService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMC
     */
    @WebEndpoint(name = "IMCPort")
    public IMC getIMCPort() {
        return super.getPort(new QName("http://world.hello/", "IMCPort"), IMC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMC
     */
    @WebEndpoint(name = "IMCPort")
    public IMC getIMCPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://world.hello/", "IMCPort"), IMC.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMCSERVICE_EXCEPTION!= null) {
            throw IMCSERVICE_EXCEPTION;
        }
        return IMCSERVICE_WSDL_LOCATION;
    }

}
