
package client.matematica;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MatematicaService", targetNamespace = "http://world.hello/", wsdlLocation = "http://127.0.0.1:9999/matematica?wsdl")
public class MatematicaService
    extends Service
{

    private final static URL MATEMATICASERVICE_WSDL_LOCATION;
    private final static WebServiceException MATEMATICASERVICE_EXCEPTION;
    private final static QName MATEMATICASERVICE_QNAME = new QName("http://world.hello/", "MatematicaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/matematica?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATEMATICASERVICE_WSDL_LOCATION = url;
        MATEMATICASERVICE_EXCEPTION = e;
    }

    public MatematicaService() {
        super(__getWsdlLocation(), MATEMATICASERVICE_QNAME);
    }

    public MatematicaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATEMATICASERVICE_QNAME, features);
    }

    public MatematicaService(URL wsdlLocation) {
        super(wsdlLocation, MATEMATICASERVICE_QNAME);
    }

    public MatematicaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATEMATICASERVICE_QNAME, features);
    }

    public MatematicaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MatematicaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Matematica
     */
    @WebEndpoint(name = "MatematicaPort")
    public Matematica getMatematicaPort() {
        return super.getPort(new QName("http://world.hello/", "MatematicaPort"), Matematica.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Matematica
     */
    @WebEndpoint(name = "MatematicaPort")
    public Matematica getMatematicaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://world.hello/", "MatematicaPort"), Matematica.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATEMATICASERVICE_EXCEPTION!= null) {
            throw MATEMATICASERVICE_EXCEPTION;
        }
        return MATEMATICASERVICE_WSDL_LOCATION;
    }

}
