
package client.matematica;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Matematica", targetNamespace = "http://world.hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Matematica {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "menorPrimo", targetNamespace = "http://world.hello/", className = "client.matematica.MenorPrimo")
    @ResponseWrapper(localName = "menorPrimoResponse", targetNamespace = "http://world.hello/", className = "client.matematica.MenorPrimoResponse")
    @Action(input = "http://world.hello/Matematica/menorPrimoRequest", output = "http://world.hello/Matematica/menorPrimoResponse")
    public int menorPrimo(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fatorial", targetNamespace = "http://world.hello/", className = "client.matematica.Fatorial")
    @ResponseWrapper(localName = "fatorialResponse", targetNamespace = "http://world.hello/", className = "client.matematica.FatorialResponse")
    @Action(input = "http://world.hello/Matematica/fatorialRequest", output = "http://world.hello/Matematica/fatorialResponse")
    public int fatorial(
        @WebParam(name = "a", targetNamespace = "")
        int a);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "maiorPrimo", targetNamespace = "http://world.hello/", className = "client.matematica.MaiorPrimo")
    @ResponseWrapper(localName = "maiorPrimoResponse", targetNamespace = "http://world.hello/", className = "client.matematica.MaiorPrimoResponse")
    @Action(input = "http://world.hello/Matematica/maiorPrimoRequest", output = "http://world.hello/Matematica/maiorPrimoResponse")
    public int maiorPrimo(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soma", targetNamespace = "http://world.hello/", className = "client.matematica.Soma")
    @ResponseWrapper(localName = "somaResponse", targetNamespace = "http://world.hello/", className = "client.matematica.SomaResponse")
    @Action(input = "http://world.hello/Matematica/somaRequest", output = "http://world.hello/Matematica/somaResponse")
    public int soma(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
